name: swd392_mobile
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.0
  firebase_messaging: ^15.2.3
  firebase_auth: ^5.5.0
  google_sign_in: ^6.2.2
  flutter_dotenv: ^5.2.1
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.1.0
  intl: ^0.18.0
  cached_network_image: ^3.3.0
  shared_preferences: ^2.5.2
  freezed_annotation: ^3.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.3
  flutter_native_splash: ^2.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo_2.png
    - assets/images/google_icon.png
    - assets/images/subscription_banner.png

  fonts:
    - family: NerkoOne
      fonts:
        - asset: assets/fonts/NerkoOne-Regular.ttf
    - family: Coiny
      fonts:
        - asset: assets/fonts/Coiny-Regular.ttf

flutter_native_splash:
  color: "#ffffff"
  branding: assets/images/logo_2.png
  android: true
  ios: true
  fullscreen: true
# flutter_launcher_icons:
#   android: true
#   ios: true
#   image_path: "assets/images/logo_2.png"
#   adaptive_icon_background: "#ffffff"
#   adaptive_icon_foreground: "assets/images/logo_2.png"
#   remove_alpha_ios: true
